import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import test from 'node:test';
import { getDueBundles, publishScheduled, validateManifest } from '../scripts/publish-scheduled.mjs';
function sample(){return {version:1,entries:[{id:'a',title:'A',source:'scheduled-content/a.astro',destination:'src/pages/guides/a/index.astro',publishAt:'2026-09-11T04:00:00Z',bundleId:'day-1',status:'queued',dependencies:[]},{id:'b',title:'B',source:'scheduled-content/b.astro',destination:'src/pages/alternatives/b/index.astro',publishAt:'2026-09-11T04:00:00Z',bundleId:'day-1',status:'queued',dependencies:[]},{id:'c',title:'C',source:'scheduled-content/c.astro',destination:'src/pages/best/c/index.astro',publishAt:'2026-09-12T04:00:00Z',bundleId:'day-2',status:'queued',dependencies:['a']}]}}
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'sv-scheduler-'));await mkdir(path.join(root,'scheduled-content'),{recursive:true});const m=sample();for(const e of m.entries)await writeFile(path.join(root,e.source),"import BaseLayout from '../../../../src/layouts/BaseLayout.astro';\nconst canonical='/x/';");const manifestPath=path.join(root,'scheduled-content/manifest.json');await writeFile(manifestPath,JSON.stringify(m));return{root,manifestPath,m}}
test('manifest rejects duplicate destinations',()=>{const m=sample();m.entries[1].destination=m.entries[0].destination;assert.throws(()=>validateManifest(m),/Duplicate destination/)});
test('schedule preserves bundle boundaries',()=>{const m=sample();assert.deepEqual(getDueBundles(m,new Date('2026-09-11T03:59:59Z')),[]);assert.deepEqual(getDueBundles(m,new Date('2026-09-11T04:00:00Z')).map(x=>x.bundleId),['day-1']);assert.deepEqual(getDueBundles(m,new Date('2026-09-12T04:00:00Z')).map(x=>x.bundleId),['day-1','day-2'])});
test('release copies only due bundle and normalizes destination imports',async t=>{const{root,manifestPath,m}=await fixture();t.after(()=>rm(root,{recursive:true,force:true}));await publishScheduled({root,manifestPath,now:new Date('2026-09-11T04:00:00Z')});const a=await readFile(path.join(root,m.entries[0].destination),'utf8');assert.match(a,/from '\.\.\/\.\.\/\.\.\/layouts\/BaseLayout\.astro'/);await assert.rejects(()=>readFile(path.join(root,m.entries[2].destination),'utf8'),{code:'ENOENT'});const updated=JSON.parse(await readFile(manifestPath,'utf8'));assert.equal(updated.entries[0].status,'published');assert.equal(updated.entries[2].status,'queued')});
test('destination collision fails before copying bundle',async t=>{const{root,manifestPath,m}=await fixture();t.after(()=>rm(root,{recursive:true,force:true}));const collision=path.join(root,m.entries[0].destination);await mkdir(path.dirname(collision),{recursive:true});await writeFile(collision,'existing');await assert.rejects(()=>publishScheduled({root,manifestPath,now:new Date('2026-09-11T04:00:00Z')}),/Refusing to overwrite/);assert.equal(await readFile(collision,'utf8'),'existing')});
