import assert from 'node:assert/strict';
import { cp, mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import test from 'node:test';
import { getDueBundles, normalizeStagedImports, publishScheduled } from '../scripts/publish-scheduled.mjs';
const repositoryRoot=path.resolve(import.meta.dirname,'..');const manifest=JSON.parse(await readFile(path.join(repositoryRoot,'scheduled-content/manifest.json'),'utf8'));const workflow=await readFile(path.join(repositoryRoot,'.github/workflows/publish-scheduled.yml'),'utf8');
test('schedule windows preserve bundle boundaries',()=>{assert.deepEqual(getDueBundles(structuredClone(manifest),new Date('2026-09-07T03:59:59Z')).map(x=>x.bundleId),[]);assert.deepEqual(getDueBundles(structuredClone(manifest),new Date('2026-09-07T04:00:00Z')).map(x=>x.bundleId),['systeme-io-2026-09-07']);assert.deepEqual(getDueBundles(structuredClone(manifest),new Date('2026-09-08T04:00:00Z')).map(x=>x.bundleId),['systeme-io-2026-09-07','systeme-io-2026-09-08'])});
async function fixture(){const root=await mkdtemp(path.join(os.tmpdir(),'selectverdict-scheduler-'));await cp(path.join(repositoryRoot,'scheduled-content'),path.join(root,'scheduled-content'),{recursive:true});return{root,manifestPath:path.join(root,'scheduled-content/manifest.json')}}
test('each scheduled release creates only its due bundle',async c=>{const{root,manifestPath}=await fixture();c.after(()=>rm(root,{recursive:true,force:true}));assert.match(workflow,/git add scheduled-content\/manifest\.json/);assert.match(workflow,/git add --all -- src\/pages\//);const a=await publishScheduled({root,manifestPath,now:new Date('2026-09-07T04:00:00Z')});assert.deepEqual(a.bundles.map(x=>x.bundleId),['systeme-io-2026-09-07']);const b=await publishScheduled({root,manifestPath,now:new Date('2026-09-08T04:00:00Z')});assert.deepEqual(b.bundles.map(x=>x.bundleId),['systeme-io-2026-09-08']);assert.equal((await publishScheduled({root,manifestPath,now:new Date('2026-09-08T04:00:00Z')})).bundles.length,0)});
test('future queue remains queued after earlier bundles publish',async c=>{const{root,manifestPath}=await fixture();c.after(()=>rm(root,{recursive:true,force:true}));await publishScheduled({root,manifestPath,now:new Date('2026-09-08T04:00:00Z')});const updated=JSON.parse(await readFile(manifestPath,'utf8'));assert.ok(updated.entries.filter(e=>Date.parse(e.publishAt)<=Date.parse('2026-09-08T04:00:00Z')).every(e=>e.status==='published'));assert.ok(updated.entries.filter(e=>Date.parse(e.publishAt)>Date.parse('2026-09-08T04:00:00Z')).every(e=>e.status==='queued'))});
test('staged imports are rewritten relative to production destination',()=>{const dest=path.join(repositoryRoot,'src/pages/alternatives/example/index.astro');const out=normalizeStagedImports("import X from '../../../../src/layouts/BaseLayout.astro';",dest,repositoryRoot);assert.equal(out,"import X from '../../../layouts/BaseLayout.astro';")});
test('an unexpected destination fails before any bundle file is copied',async c=>{const{root,manifestPath}=await fixture();c.after(()=>rm(root,{recursive:true,force:true}));const collision=path.join(root,manifest.entries[0].destination);await mkdir(path.dirname(collision),{recursive:true});await writeFile(collision,'existing');await assert.rejects(()=>publishScheduled({root,manifestPath,now:new Date('2026-09-07T04:00:00Z')}),/Refusing to overwrite existing destination/);assert.equal(await readFile(collision,'utf8'),'existing')});
